### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xphp#41]
In order to launch we should have:

- [x] php as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] at least 10 problems
- [x] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-php.md`)
- [ ] convert wordy to pure function
- [x] convert trinary to pure function
- [x] convert roman-numerals to pure function
- [x] one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot
- [ ] toggle `"active"` to `true` in `config.json`

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* each submission receives feedback quickly, preferably within the first 24 hours
* the nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by kytrinyx** [comment]
Notes: @arcdigital and @jeliastam have offered to nitpick (thank you!)

@Dog suggested (https://github.com/exercism/exercism.io/issues/2036#issuecomment-68612451) that these three problems should be updated to use pure  functions: Wordy, Trinary, Roman-Numerals. (updated checklist to include this).

**Comment by Dog** [comment]
I converted roman-numerals.

The last two are trinity and wordy.

**Comment by petemcfarlane** [comment]
Hi, I just submitted a pull request #43 converting wordy to a function, I'd like to help with some other stuff too to get the PHP track ready to launch.

**Comment by LucasThompson** [comment]
I've submitted a pull request #44 for converting trinary to a pure function.  I'm also eager to get the PHP track out in the wild.

**Comment by petemcfarlane** [comment]
So as far as I can see there are some of us who have agreed to nitpick, we have a 'getting started' page, and the exercises have been converted. Can we now make this active?

**Comment by kytrinyx** [comment]
Done!

I'm deploying now. I'll make sure y'all have nitpicker access on the track.

Thank you, everyone!

**Comment by arcdigital** [comment]
Awesome!

**Comment by jeliastam** [comment]
I've been looking forward to this.  Ready to contribute.



—

**Comment by kytrinyx** [comment]
@LucasThompson do you want to be a designated nitpicker as well, or would you like to sit back and enjoy the critique from the others?

**Comment by LucasThompson** [comment]
@kytrinyx happy to nitpick!

**Comment by jeliastam** [comment]
Do you have a sufficient number of nitpickers?  I could ask a couple of co workers if they are interested.



—

**Comment by kytrinyx** [comment]
@jeliastam I think having a couple extra people on hand would be fantastic.

**Comment by kytrinyx** [comment]
@LucasThompson -- I've added you as a designated nitpicker. Thanks!

**Comment by Dog** [comment]
@kytrinyx 

I'm having problems seeing other people's submissions. I see a grand total of 4 PHP submissions, but the "Have a moment?" call to action asks me to nitpick on solutions not listed under nitpick.

**Comment by jeliastam** [comment]
No issues here, nitpickin’ away.


—
